apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: {{ .Values.namespace }}
  labels:
    app: java-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080  # 根据你的Java应用实际监听端口修改
  selector:
    app: java-app
